### ISSUE TITLE
Limit query execution by work AKA hops query limit

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1374]
`USING HOPS LIMIT 100000 MATCH (n1)-[bfs*]->(n2) RETURN n2;`

### TODOs

- [x] Measure and expose hops back to the user (BFS+DFS+Expand; if an edge is filtered out, it should count as a hop)
- [x] Implement the syntax
- [x] Limit the execution
- [x] Add option to return partial results
- [ ] OPTIONAL/NEXT/NOT_REQUIRED: Implement `HOPS LIMIT` under more advanced variable-expand options (`wShortest`, `allShortest`)

**Comment by as51340** [comment]
@gitbuda Do we talk here about absolute number of hops which would basically mean every possible expand we do or we talk neigborhood, like 2-hop neighborhood?

**Comment by gitbuda** [comment]
> @gitbuda Do we talk here about absolute number of hops which would basically mean every possible expand we do or we talk about neigborhood, like 2-hop neighborhood?

Every edge traversed because the traversal depth is already possible to limit under variable expand, e.g., `bfs*..2` 😃
