### ISSUE TITLE
Extend and improve HA automatic failover capabilities 

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1915]
### TODO's

- [x] Make HA API k8s / cloud ready
- [x] Introduce better Jepsen tests and fix issues - single region test case
- [x] Make sure all mayor Bolt drivers (`bolt+routing`) are supported

### DONE

* https://github.com/memgraph/memgraph/pull/1902
* https://github.com/memgraph/memgraph/pull/1911
* https://github.com/memgraph/memgraph/pull/1912

Previous work under https://github.com/memgraph/memgraph/issues/1143

**Comment by gitbuda** [comment]
I consider this done, we'll open new issues if needed, most likely for the multi-region HA automatic failover setup.
