### ISSUE TITLE
[EPIC] Enum datatype

### ISSUE THREAD

**Issue by Ignition** [memgraph/memgraph#2042]
Epic to track PRs relating to the Enum datatype + cypher changes.

- [x] enum store
- [ ] durability
  - [x] snapshot
  - [x] wal
  - [ ] enum property value stability (not part of mvp)
- [x] replication
- [x] cypher creation
- [x] cypher show
- [x] cypher use
- [ ] cypher drop (not part of mvp)
- [x] cypher add value
- [x] cypher update value
- [ ] cypher remove value (not part of mvp)
- [x] replication
- [ ] mgconsole pretty print (memgraph/mgconsole#73)
